// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOPrXQAi3BQ-vtsIa6E_O32-Ra6lyVqXE',
    appId: '1:607150892347:web:0070c3dae7329bec3c831e',
    messagingSenderId: '607150892347',
    projectId: 'smdproject-3ad33',
    authDomain: 'smdproject-3ad33.firebaseapp.com',
    storageBucket: 'smdproject-3ad33.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZaO7vD8CcjI9RIb1AdTh6PYsgMzzkgsA',
    appId: '1:607150892347:android:96fe84f2204b3b0b3c831e',
    messagingSenderId: '607150892347',
    projectId: 'smdproject-3ad33',
    storageBucket: 'smdproject-3ad33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTm7n3zbTiEOJASWe01E6R9OEJsF207Fk',
    appId: '1:607150892347:ios:290b7f00dc93c8913c831e',
    messagingSenderId: '607150892347',
    projectId: 'smdproject-3ad33',
    storageBucket: 'smdproject-3ad33.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTm7n3zbTiEOJASWe01E6R9OEJsF207Fk',
    appId: '1:607150892347:ios:290b7f00dc93c8913c831e',
    messagingSenderId: '607150892347',
    projectId: 'smdproject-3ad33',
    storageBucket: 'smdproject-3ad33.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOPrXQAi3BQ-vtsIa6E_O32-Ra6lyVqXE',
    appId: '1:607150892347:web:3fe7776debcb15783c831e',
    messagingSenderId: '607150892347',
    projectId: 'smdproject-3ad33',
    authDomain: 'smdproject-3ad33.firebaseapp.com',
    storageBucket: 'smdproject-3ad33.firebasestorage.app',
  );
}
